### ISSUE TITLE
Note and warning boxes doubling titles

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast-docs-ui#154]
Found a funny visual bug - if I open a page that has a "note" or "warning" box there, the caption is doubled, see the screenshot. It disappears in like half of a second. Took me a while to capture it with print screen :smile: Reproducible on the everywhere on the live docs, e.g. here: https://docs.hazelcast.com/hazelcast/latest/clusters/discovery-mechanisms (happens on every refresh)
![Snímek z 2022-01-28 12-22-42](https://user-images.githubusercontent.com/4253850/151542982-26119ef0-873f-488e-941c-c46923ed533d.png)

**Comment by JakeSCahill** [comment]
We haven't had any reports of this since. I'll close it for now and reopen if it crops up again.
