### ISSUE TITLE
Docs: Feedback for different display sizes

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast-docs-ui#83]
Hi, I have some feedback about how space on different displays is used.
This is how docs look like on my MacBook 13" display
<img width="1440" alt="MacBook 13" src="https://user-images.githubusercontent.com/5074607/108351554-5c528880-71ee-11eb-8a67-f5066a9a2b0f.png">

This is how it looks like on MacBook 16" display
<img width="1792" alt="MacBook 16" src="https://user-images.githubusercontent.com/5074607/108351631-742a0c80-71ee-11eb-91da-f2a91daeec8f.png">

And this is how it looks like on Dell Monitor with 27" diagonal
<img width="2560" alt="Dell Monitor 27" src="https://user-images.githubusercontent.com/5074607/108351691-86a44600-71ee-11eb-9c9f-d004ea8d7f0f.png">

We don't use all advantages of big screens.

For example this is [one of the Cockroachdb doc page](https://www.cockroachlabs.com/docs/v20.2/recommended-production-settings) looks like on my Dell Monitor
<img width="2560" alt="CockroachDb doc 27" src="https://user-images.githubusercontent.com/5074607/108351992-e7cc1980-71ee-11eb-8e8d-327a111cf276.png">

and this is how the same page looks like on the MacBook 16" display
<img width="1792" alt="CockroachDb doc 16" src="https://user-images.githubusercontent.com/5074607/108352045-fca8ad00-71ee-11eb-8f0f-6aff2e2e2039.png">

**Comment by JakeSCahill** [comment]
Thanks @alex-dukhno. This would certainly be an improvement 👍
